### ISSUE TITLE
Error while starting notion-app

### ISSUE THREAD

**Issue by ghost** [notion-enhancer/notion-repackaged#120]
When I start the notion-app, I get this error message:

`Error: Error: ENOENT: no such file or directory, open '/opt/Notion/resources/app-update.yml'`.

I am using Fedora 38 and I installed it from the yum repository.

**Comment by dragonwocky** [comment]
Try creating a text file in the `/opt/Notion/resources` folder and naming it `app-update.yml`

**Comment by ghost** [comment]
After creating the file I get the following error message:

`
Error: TypeError: Cannot read property 'provider' of undefined
    at createClient (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/providerFactory.js:69:25)
    at /opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:479:99
    at async AppImageUpdater.getUpdateInfoAndProvider (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:482:20)
    at async AppImageUpdater.doCheckForUpdates (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)
    at async pollForElectronUpdates (/opt/Notion/resources/app.asar/main/autoUpdater.js:163:17)`

**Comment by dragonwocky** [comment]
Right, sorry - just double checked, the auto updater only works on Windows, so that file was intentionally left non-existent. Delete the file and you should be able to ignore the `ENOENT` error safely. If you're having infinite loading issues, they're unrelated to this error message, please see https://github.com/notion-enhancer/notion-repackaged/issues/116
