### ISSUE TITLE
Notion-app-enhancer never start, hang up with white screen with a circle of loading at start up (Fedora)

### ISSUE THREAD

**Issue by hhlp** [notion-enhancer/notion-repackaged#126]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**

Notion-app-enhancer never start, hang up with white screen with a circle of loading at start up (Fedora)

**What should be happening?**

start and be avalilable to work with it via MENU

**Screenshots (if applicable):**

![Captura desde 2024-02-18 20-08-34](https://github.com/notion-enhancer/notion-repackaged/assets/2659606/3f7a67eb-e73c-49f9-b046-6792a9e75e66)

**Operating system/browser name & version:**

fedora: 39
linux:    x86_64

**notion-enhancer and/or notion-repackaged version:**

notion for desktop installed via fedora repo:

```
[notion-repackaged]
name=notion-repackaged
baseurl=https://yum.fury.io/notion-repackaged/
enabled=1
gpgcheck=0
```

```
rpm -qa notion\*
notion-app-enhanced-2.0.18-1.x86_64
```

**notion-enhancer configuration (enabled/disabled mods and their settings):**

default config, never touched

**Log**

```

🕙 20:20:34 ➜ notion-app-enhanced 

(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
20:20:38.826 › { level: 'info', from: 'AssetCache', type: 'checkingForAppUpdate' }
20:20:38.843 › Checking for update
20:20:39.120 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/hhlp/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
20:20:39.121 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
20:20:39.122 › {
  level: 'info',
  from: 'autoUpdater',
  type: 'unsupportedLinuxApp',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'",
    stack: "Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'"
  }
}
20:20:39.123 › {
  level: 'info',
  from: 'AssetCache',
  type: 'errorReadingPath',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/home/hhlp/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'",
    stack: "Error: ENOENT: no such file or directory, open '/home/hhlp/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'"
  },
  data: {
    message: 'Error reading /home/hhlp/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
20:20:39.123 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: {}
}


20:20:39.123 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionEmptyLatestVersion'
}
20:20:39.124 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: {}
}
(node:32558) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
20:20:39.156 › { level: 'info', from: 'AssetCache', type: 'noAppUpdateAvailable' }
20:20:39.222 › Websocket listening on 45813...
20:20:39.225 › Set up server listeners with auth (f063c9a9b12e07337540ea87d4ea25c6ee6d0aab)...
(node:32558) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:32558) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
20:20:39.745 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.748 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}


20:20:39.755 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.758 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.760 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}

20:20:39.763 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.766 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.769 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}


20:20:39.771 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.774 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.777 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}


20:20:39.781 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.796 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.798 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}


20:20:39.801 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.805 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.807 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}



20:20:39.814 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.816 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.818 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}


20:20:39.823 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:39.930 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:40.532 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app.asar/main/schemeHandler.js:221:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
20:20:42.245 › Quitting...
20:20:42.245 › Killing child process
20:20:42.246 › Responding to SIGTERM and shutting down...


```

**NOTES**

Worked well under fedora 38.

I've also tried this without sucess

```
rm -r ~/.config/notion-app-enhanced
```

Regards.,

**Comment by serpro69** [comment]
Same issue on PopOS 22.04 
```
➜ lsb_release -a
No LSB modules are available.
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy

~ …
➜ uname -a
Linux 6.6.6-76060606-generic SMP PREEMPT_DYNAMIC Mon D x86_64 x86_64 x86_64 GNU/Linux
```

Tried a regular version and "enhanced" via AppImage, neither went beyond the loading screen.

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-repackaged/issues/116, see it for a workaround
