### ISSUE TITLE
latest-linux.yml doesn't exist for v2.0.18-1

### ISSUE THREAD

**Issue by iainvm** [notion-enhancer/notion-repackaged#131]
**What is happening?**
- Installed the app through `nix`
- Launch the app
- Loading infinitely
- Logs show it tried to read `latest-linux.yml` for the `v2.0.18-1` release

**What should be happening?**
It should load, and not look for a file that doesn't exist

**Screenshots (if applicable):**
```
{
  level: 'info',
  from: 'autoUpdater',
  type: 'unsupportedLinuxApp',
  error: {
    statusCode: 404,
    name: 'HttpError',
    message: '404 \n' +
      '"method: GET url: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/latest-linux.yml\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n"\n' +
      'Headers: {\n' +
      '  "server": "GitHub.com",\n' +
      '  "date": "Fri, 28 Jun 2024 17:08:29 GMT",\n' +
      '  "content-type": "text/plain; charset=utf-8",\n' +
      '  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",\n' +
      '  "cache-control": "no-cache",\n' +
      '  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",\n' +
      '  "x-frame-options": "deny",\n' +
      '  "x-content-type-options": "nosniff",\n' +
      '  "x-xss-protection": "0",\n' +
      '  "referrer-policy": "no-referrer-when-downgrade",\n' +
      `  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",\n` +
      '  "content-encoding": "gzip",\n' +
      '  "content-length": "29",\n' +
      '  "x-github-request-id": "9806:23E95F:CAF079:E0156A:667EEE0D"\n' +
      '}',
```

**Operating system/browser name & version:**
NixOS
(Package)[https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/office/notion-app-enhanced/default.nix]

**notion-enhancer and/or notion-repackaged version:**
2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
None

**Comment by cloudmaker97** [comment]
I can reproduce this on Debian 12 Bookworm

```
00:05:50.985 › Error: HttpError: 404 
"method: GET url: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 14 Aug 2024 22:05:04 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "994A:3D5A1A:4286E99:43B8967:66BD2A3E"
}
    at createHttpError (/tmp/.mount_NotionQjIOPy/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_NotionQjIOPy/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:167:14)
    at ClientRequest.<anonymous> (/tmp/.mount_NotionQjIOPy/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:133:16)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)
00:05:50.986 › {
  level: 'info',
  from: 'autoUpdater',
  type: 'unsupportedLinuxApp',
  error: {
    statusCode: 404,
    name: 'HttpError',
    message: '404 \n' +
      '"method: GET url: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/latest-linux.yml\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n"\n' +
      'Headers: {\n' +
      '  "server": "GitHub.com",\n' +
      '  "date": "Wed, 14 Aug 2024 22:05:04 GMT",\n' +
      '  "content-type": "text/plain; charset=utf-8",\n' +
      '  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",\n' +
      '  "cache-control": "no-cache",\n' +
      '  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",\n' +
      '  "x-frame-options": "deny",\n' +
      '  "x-content-type-options": "nosniff",\n' +
      '  "x-xss-protection": "0",\n' +
      '  "referrer-policy": "no-referrer-when-downgrade",\n' +
      `  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",\n` +
      '  "content-encoding": "gzip",\n' +
      '  "content-length": "29",\n' +
      '  "x-github-request-id": "994A:3D5A1A:4286E99:43B8967:66BD2A3E"\n' +
      '}',
    stack: 'HttpError: 404 \n' +
      '"method: GET url: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/latest-linux.yml\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n"\n' +
      'Headers: {\n' +
      '  "server": "GitHub.com",\n' +
      '  "date": "Wed, 14 Aug 2024 22:05:04 GMT",\n' +
      '  "content-type": "text/plain; charset=utf-8",\n' +
      '  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",\n' +
      '  "cache-control": "no-cache",\n' +
      '  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",\n' +
      '  "x-frame-options": "deny",\n' +
      '  "x-content-type-options": "nosniff",\n' +
      '  "x-xss-protection": "0",\n' +
      '  "referrer-policy": "no-referrer-when-downgrade",\n' +
      `  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",\n` +
      '  "content-encoding": "gzip",\n' +
      '  "content-length": "29",\n' +
      '  "x-github-request-id": "994A:3D5A1A:4286E99:43B8967:66BD2A3E"\n' +
      '}\n' +
      '    at createHttpError (/tmp/.mount_NotionQjIOPy/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)\n' +
      '    at ElectronHttpExecutor.handleResponse (/tmp/.mount_NotionQjIOPy/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:167:14)\n' +
      '    at ClientRequest.<anonymous> (/tmp/.mount_NotionQjIOPy/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:133:16)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
```

**Comment by sadtank** [comment]
Same issue. Fresh install of NixOS and app.

[notion-app-enhanced](https://search.nixos.org/packages?channel=24.11&show=notion-app-enhanced&from=0&size=50&sort=relevance&type=packages&query=notion-app-enhanced)

```
$ nixos-version 
24.05.6966.190c31a89e5e (Uakari)
```

```
22:38:23.600 › {
  level: 'info',
  from: 'autoUpdater',
  type: 'unsupportedLinuxApp',
  error: {
    statusCode: 404,
    name: 'HttpError',
    message: '404 \n' +
      '"method: GET url: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/latest-linux.yml\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n"\n' +
      'Headers: {\n' +
      '  "server": "GitHub.com",\n' +
      '  "date": "Sun, 08 Dec 2024 06:38:23 GMT",\n' +
      '  "content-type": "text/plain; charset=utf-8",\n' +
      '  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",\n' +
      '  "cache-control": "no-cache",\n' +
      '  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",\n' +
      '  "x-frame-options": "deny",\n' +
      '  "x-content-type-options": "nosniff",\n' +
      '  "x-xss-protection": "0",\n' +
      '  "referrer-policy": "no-referrer-when-downgrade",\n' +
      `  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",\n` +
      '  "content-encoding": "gzip",\n' +
      '  "content-length": "29",\n' +
      '  "x-github-request-id": "BE72:29401A:A0586BD:A414A3F:67553EDF"\n' +
      '}',
    stack: 'HttpError: 404 \n' +
      '"method: GET url: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/latest-linux.yml\\n\\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\\n"\n' +
      'Headers: {\n' +
      '  "server": "GitHub.com",\n' +
      '  "date": "Sun, 08 Dec 2024 06:38:23 GMT",\n' +
      '  "content-type": "text/plain; charset=utf-8",\n' +
      '  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",\n' +
      '  "cache-control": "no-cache",\n' +
      '  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",\n' +
      '  "x-frame-options": "deny",\n' +
      '  "x-content-type-options": "nosniff",\n' +
      '  "x-xss-protection": "0",\n' +
      '  "referrer-policy": "no-referrer-when-downgrade",\n' +
      `  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",\n` +
      '  "content-encoding": "gzip",\n' +
      '  "content-length": "29",\n' +
      '  "x-github-request-id": "BE72:29401A:A0586BD:A414A3F:67553EDF"\n' +
      '}\n' +
      '    at createHttpError (/nix/store/jqg235vz92wdrkk2185ixiq4ahh546pb-notion-app-enhanced-2.0.18-1-extracted/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)\n' +
      '    at ElectronHttpExecutor.handleResponse (/nix/store/jqg235vz92wdrkk2185ixiq4ahh546pb-notion-app-enhanced-2.0.18-1-extracted/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:167:14)\n' +
      '    at ClientRequest.<anonymous> (/nix/store/jqg235vz92wdrkk2185ixiq4ahh546pb-notion-app-enhanced-2.0.18-1-extracted/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:133:16)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:483:12)'
  }
}
```
