### ISSUE TITLE
cannot run on Linux Mint

### ISSUE THREAD

**Issue by TheFirstQuestion** [notion-enhancer/notion-repackaged#60]
I'm attempting to install notion-repackaged on my Linux Mint laptop. I had the same issue as #55, so tried to use the .deb instead. In both cases, upon running notion-app-enhanced, a white windows opens with a loading symbol and the tray icon shows up, but nothing else ever happens. When running from terminal, the output is as follows:

```
$ notion-app-enhanced 
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
16:06:16.014 › Checking for update
16:06:16.088 › Error reading /home/sophie/.config/notion-app-enhanced/cookies.json {
  constructor: 'Error',
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/sophie/.config/notion-app-enhanced/cookies.json',
  stack: "Error: /home/sophie/.config/notion-app-enhanced/cookies.json: ENOENT: no such file or directory, open '/home/sophie/.config/notion-app-enhanced/cookies.json'\n" +
    '    at Object.openSync (fs.js:466:3)\n' +
    '    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)\n' +
    '    at Object.readFileSync (fs.js:368:35)\n' +
    '    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8592)\n' +
    '    at Object.readFileSync (/opt/Notion Enhanced/resources/app/node_modules/jsonfile/index.js:61:22)\n' +
    '    at JsonStore.loadSync (/opt/Notion Enhanced/resources/app/main/JsonStore.js:37:44)\n' +
    '    at new JsonStore (/opt/Notion Enhanced/resources/app/main/JsonStore.js:14:14)\n' +
    '    at Object.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:24:25)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1152:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)'
}
(node:7468) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
16:06:16.302 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/sophie/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
16:06:16.306 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
16:06:16.307 › {
  level: 'info',
  from: 'AssetCache',
  type: 'errorReadingPath',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/home/sophie/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'",
    stack: "Error: ENOENT: no such file or directory, open '/home/sophie/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'"
  },
  data: {
    message: 'Error reading /home/sophie/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
16:06:16.308 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: {}
}
16:06:16.310 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionEmptyLatestVersion'
}
16:06:16.311 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: {}
}
16:06:16.343 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'focused_window.isMaximized is not a function',
    stack: 'TypeError: focused_window.isMaximized is not a function\n' +
      '    at Object.__exports.createWindow (/opt/Notion Enhanced/resources/app/embedded_enhancer/mods/core/createWindow.js:42:43)\n' +
      '    at handleActivate (/opt/Notion Enhanced/resources/app/main/main.js:71:36)\n' +
      '    at startup (/opt/Notion Enhanced/resources/app/main/main.js:149:5)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  }
}
(node:7468) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:7468) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
16:06:25.536 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
16:06:25.551 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
16:06:25.562 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
16:06:25.607 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
16:06:25.627 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
16:06:25.638 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
16:06:25.658 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
^C16:06:45.426 › Quitting...
16:06:45.427 › Killing child process
```

I've tried removing and reinstalling, and deleting the folder in /opt and /.config, to no avail. 

Link to full system info: https://termbin.com/w4hq
Distro: Linux Mint 19.1 Tessa (base: Ubuntu 18.04 bionic)

Please let me know what other information I can provide! Thanks in advance :D

**Comment by everyx** [comment]
Same problem here on Arch Linux with `aur/notion-app-enhanced 2.0.16-7`

**Comment by dpertierra** [comment]
Same problem on Fedora, downloaded from their repo

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-repackaged/issues/63
