### ISSUE TITLE
autoupdater failing on linux

### ISSUE THREAD

**Issue by jackheuberger** [notion-enhancer/notion-repackaged#63]
Tried installing the regular and enhanced versions via the AUR. Getting the following console output upon running `notion-app`:

```[jackh@darlene-arch ~]$ notion-app
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
19:31:20.279 › Checking for update
19:31:20.701 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/jackh/.config/notion-app/notionAssetCache-v2/latestVersion.json'
  }
}
19:31:20.705 › {
  level: 'info',
  from: 'AssetCache',
  type: 'errorReadingPath',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/home/jackh/.config/notion-app/notionAssetCache-v2/latestVersion.json'",
    stack: "Error: ENOENT: no such file or directory, open '/home/jackh/.config/notion-app/notionAssetCache-v2/latestVersion.json'"
  },
  data: {
    message: 'Error reading /home/jackh/.config/notion-app/notionAssetCache-v2/latestVersion.json'
  }
}
19:31:20.705 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: {}
}
19:31:20.706 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionEmptyLatestVersion'
}
19:31:20.706 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: {}
}
(node:9982) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:9982) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
19:31:20.774 › Error: TypeError: Cannot read property 'provider' of undefined
    at createClient (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/providerFactory.js:69:25)
    at /opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:479:99
    at async AppImageUpdater.getUpdateInfoAndProvider (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:482:20)
    at async AppImageUpdater.doCheckForUpdates (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)
    at async pollForElectronUpdates (/opt/Notion/resources/app.asar/main/autoUpdater.js:147:17)
19:31:20.775 › {
  level: 'error',
  from: 'autoUpdater',
  type: 'unknownAutoUpdaterError',
  error: {
    name: 'TypeError',
    message: "Cannot read property 'provider' of undefined",
    stack: "TypeError: Cannot read property 'provider' of undefined\n" +
      '    at createClient (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/providerFactory.js:69:25)\n' +
      '    at /opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:479:99\n' +
      '    at async AppImageUpdater.getUpdateInfoAndProvider (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:482:20)\n' +
      '    at async AppImageUpdater.doCheckForUpdates (/opt/Notion/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)\n' +
      '    at async pollForElectronUpdates (/opt/Notion/resources/app.asar/main/autoUpdater.js:147:17)'
  }
}
19:31:20.843 › Websocket listening on 43521...
19:31:20.846 › Set up server listeners with auth (a16878de9fa15dc8cf6716544f23aa0ddb00602a)...```

**Comment by illuz** [comment]
I have the same problem in Arch.

**Comment by luke-wriglesworth** [comment]
Also having the problem

**Comment by cnJayceon** [comment]
Also having the problem

**Comment by ZloyPirozhok** [comment]
I also don't start the system after updating.

**Comment by zJairO** [comment]
Same problem here..

**Comment by zJairO** [comment]
Think is a problem with contextIsolation on Electron

**Comment by dragonwocky** [comment]
@zJairO it's an autoupdater problem, it will be solved once the enhancer updates to the latest notion version.

**Comment by JCDetwiler** [comment]
A reminder for anyone else like me that needs it: Notion has a web client too. https://www.notion.so/

**Comment by raquel-dantas** [comment]
Any news?

**Comment by LucStr** [comment]
Would be nice to get an update on this :)

**Comment by dragonwocky** [comment]
the news is that I'm working on it. the fix for this will be released at the same time as the fix for the 100+ other bugs is released.

**Comment by LaurentOngaro** [comment]
A good work arround is to create a web app using [webapp-manager](https://github.com/linuxmint/webapp-manager)
juste create a new app pointing to www.notion.so. 
Log in and it's done !

**Comment by farzadmf** [comment]
I used [nativefier](https://github.com/nativefier/nativefier) to create an app, but I find that the experience with this app (when it works of course) is a bit better
