### ISSUE TITLE
[sql error] infinite loading

### ISSUE THREAD

**Issue by notprash** [notion-enhancer/notion-repackaged#65]
![image](https://user-images.githubusercontent.com/67903361/144855032-5a88abad-9f14-4288-a38f-b69f2f9dd737.png)
I am stuck at the loading page. No pop up for signing in

**Comment by flash872** [comment]
Same issue for me. Posting by another user over here, too: https://aur.archlinux.org/packages/notion-app/#comment-838403

**Comment by isteqra** [comment]
Same issue for me. Form mx19.4 , i try use form deb package and appimage

**Comment by JuliusMaschine** [comment]
Isn't this the same issue as the autoupdater failing?

**Comment by flash872** [comment]
I'm not sure of this--and I'm not sure it's helpful, but it happened the other day right after I got an arch update of electron from the standard repos. Next boot, I lost the ability to access data from the desktop application. Online/ web access is fine, of course. It could have been another package update than electron I suppose.

**Comment by cortex** [comment]
I have the same issue, using this package via Arch AUR. Here is what I'm guessing the relevant error in text format:

```
Uncaught (in promise) SqliteSchemaMismatch: schema failed validation: schema.tables.notion.columns[0].type should be `"integer"`, instead was `"INTEGER"`.
    at h (notion://www.notion.so/app-52b0952….js:1:5138217)
    at te (notion://www.notion.so/app-52b0952….js:1:3525469)
    at Q (notion://www.notion.so/app-52b0952….js:1:3522551)
    at async se.ensureMigrated (notion://www.notion.so/app-52b0952….js:1:3526339)
    at async Module.ie (notion://www.notion.so/app-52b0952….js:1:331986)
    at async notion://www.notion.so/app-52b0952….js:1:3494439

```

**Comment by cortex** [comment]
```
2021-12-07T11:26:26.008Z [info] sqliteSchemaHelpers: attemptMigration:  Attempting migration from 19 to 20
2021-12-07T11:26:26.057Z [info] sqliteSchemaHelpers: successfulMigration:  Successfully migrated to 20 Object
```
It also logs this right before the error, possibly relevant.

**Comment by Dam-Buty** [comment]
I'm having the same issue with the AUR package and can confirm it's not the same issue as https://github.com/notion-enhancer/notion-repackaged/issues/37 . LMK if i can help with some logs / additional information

**Comment by Tupu4545** [comment]
Same issue no activity in network tab also
